version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - 'path.repo=/usr/share/opensearch/backup'
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./opensearch-backup:/usr/share/opensearch/backup
#      - ./dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    command: >
      bash -c "./bin/opensearch-plugin list | grep -q analysis-nori
      || ./bin/opensearch-plugin install analysis-nori;
      /usr/share/opensearch/opensearch-docker-entrypoint.sh"


  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net

  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --port 6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=changeme
    restart: always
    ports:
      - "6379:6379"

volumes:
  opensearch-data1:

networks:
  opensearch-net:
