spring:
  application:
    name: ecommerce-search-api
  profiles:
    active: local
  config:
    import:
      - kafka.yaml
      - opensearch.yaml

feign:
  url:
    model-api: 'http://localhost:8000'

server:
  port: 8080
